### ISSUE TITLE
Suggestion: Added invisible

### ISSUE THREAD

**Issue by httpRick** [Patrick2562/mtasa-pAttach#12]
Export function:
invisible(ped, object, bool)

Adding the invisible option for one object, for example, I have a grenade and I throw it, I want to hide the object for a moment that I supposedly threw it and not detach it from the player's hand then reappear it

**Comment by Fernando-A-Rocha** [comment]
+1
Maybe setVisible true/false

**Comment by gptrk0** [comment]
Added with 44d2170605e4476210cf53e11397746b21b23a3b
