### ISSUE TITLE
Add option to disable toggling collision of attached object

### ISSUE THREAD

**Issue by CrosRoad95** [Patrick2562/mtasa-pAttach#14]
I want to manually control when collision of particular object is enabled or not, so i need some kind of property that hand control over "setElementCollisionEnabled" to my code instead of pAttach

**Comment by gptrk0** [comment]
_setElementCollisionEnabled_ is called when the element is attached/deattached.
Is it not enough for you to call **setElementCollisionEnabled(e, true)** directly after attach?

**Comment by CrosRoad95** [comment]
From my tests it doesn't work, calling attach from server and slipe-server

**Comment by Patrick2562** [comment]
#15

**Comment by Patrick2562** [comment]
Closed by #15

**Comment by gptrk0** [comment]
Closed by https://github.com/Patrick2562/mtasa-pAttach/pull/15
