### ISSUE TITLE
invisibleAll / setElementAlpha doesn't work on attached elements

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [Patrick2562/mtasa-pAttach#4]
I noticed that you can't **setElementAlpha** on attached elements using the invisibleAll function.
I made an additional invisible function to change only a single attached element, and same result.

Didn't investigate further, but can you confirm this?

**Comment by gptrk0** [comment]
If I understand correctly you want to change alpha of an attached object, but it doesn't change.
**invisibleAll** functions works fine for me, and I can change alpha of a single attached object with setElementAlpha directly.
- Note that objects became invisible under **140** alpha value.
