### ISSUE TITLE
Mixed Bone ID documentation

### ISSUE THREAD

**Issue by PlatinMTA** [Patrick2562/mtasa-pAttach#6]
I think that there are some bones mixed on the Bones IDs & Names section of the documentation.

Head (ID: 8) seems to actually be the Jaw, and Neck 2 (ID: 5) seems to actually be the Head. Neck 2 really does not exist. When you attach an object to ID 8 it will move alongside your jaw (some walking animations move your jaw, so it's easier to see it like that).

You can also open up Blender, import a Skin and see which bone is were. For example using Blender, the one that is more close to the mouth (ID: 8) is called the Jaw, and it moves the jaw. While the other (ID: 5) is called the Head, and it moves the head.

![image](https://user-images.githubusercontent.com/23291573/161589778-de7cdd00-b2a4-423b-8dd2-6b4383ef3716.png)
![image](https://user-images.githubusercontent.com/23291573/161590199-a54afb99-2a96-47ef-918e-aa776e691b2a.png)

You can see this in game.

![image](https://user-images.githubusercontent.com/23291573/161590253-ad482d79-40f7-40d3-81cc-c2d20c275868.png)

Here are some videos (debug chat shows the Bone ID that is being used)
https://youtu.be/kpbhIjNGwr4
https://youtu.be/OAe9noSNatI

This also seems to be wrong on the wiki (4 is called uppertorso and 5 neck, when 4 is neck [this is technically correct since the neck bone kinda moves all of the upper torso but still] and 5 is head [5 is definitely head])

**Comment by iiroak** [comment]
The person above me is absolutely right, I have been adjusting a helmet for hours and the problem is that the numbers on the list were wrong.

`exports.pattach:attach(players[thePlayer].player_elements.helmet, thePlayer, 5, px, py, (pz + fixH), rx + 90, ry, rz)`

![Screenshot_1](https://user-images.githubusercontent.com/55340002/163900268-bcd79754-6ffb-416a-acd2-7602d6c9a04f.png)

**Comment by gptrk0** [comment]
Hey, thanks for your feedback, looks like you are right.
I'm gonna figure out which is the best way to rename them without causing too much trouble for people.

**Comment by gptrk0** [comment]
[3a70120](https://github.com/Patrick2562/mtasa-pAttach/commit/3a701209506377ba1351fd6d1b787bbc56bc6bab)
