### ISSUE TITLE
Error with attaching; mistake in readme

### ISSUE THREAD

**Issue by nikitafloy** [Patrick2562/mtasa-pAttach#9]
Hello)

My server-side example:
`	local object = Object(330, 0, 0, 0)
exports.pAttach:attach(object, player, 24, 0, 0, 0, 0, 0, 0)`

I got:

> Expected element (except: player) at argument 1, got userdata

On server-side of my script object is element and object.

Another things:
I think, you have a mistake here:
https://github.com/Patrick2562/mtasa-pAttach#how-to-use

"Server sided example", but you use client-side localPlayer and do not use first player-argument of addCommandHandler function.

**Comment by gptrk0** [comment]
Woops, my bad. Thanks
